site_name: Roar User Guide
site_url: https://docs.icds.psu.edu
site_description: User documentation for the Roar Supercomputer hosted by the Institute of Computational and Data Sciences at the Pennsylvania State University.
site_author: Institute of Computational and Data Sciences
#repo_url: https://github.com/PSU-ICDS/icds_docs
#edit_url: edit/staging/docs/

theme: 
  name: material
  features:
    - content.code.copy
    - navigation.sections
    - navigation.expand
    - toc.follow
  highlightjs: true
  logo: img/PSU_ICDS_logo_blue.png
  site_favicon: img/favicon.ico
  next_previous: true

repo_url: https://github.com/PSU-ICDS/icds_docs
edit_url: null

copyright: 'Contribute to this documentation at <a href="https://github.com/PSU-ICDS/icds_docs">https://github.com/PSU-ICDS/icds_docs</a>'

extra:
  generator: false
#extra_footer: |
#  [Contribute to this project](https://github.com/PSU-ICDS/icds_docs/CONTRIBUTING.md)


extra_css: 
    - css/extra.css

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - attr_list

plugins:
#    - bootstrap4-blockquotes
#    - bootstrap4-tables
 
nav:
    - Getting started: 
        - getting-started/tips-for-beginners.md
        - getting-started/glossary.md
        - getting-started/connecting.md
        - getting-started/frequently-asked-questions.md
        - getting-started/getting-help.md
    - System details:
        - system/system-overview.md
        - system/compute-hardware.md
        - system/system-outages.md
    - Accounts:
        - accounts/paid-resources.md
        - accounts/managing-compute.md
        - accounts/managing-storage.md
    - File system:
        - file-system/file-storage.md
        - file-system/managing-files.md
        - file-system/finding-files.md
        - file-system/transferring-files.md
    - Software:
        - software/modules.md
        - software/installing-from-source.md
        - software/custom-modules.md
        - software/containers.md
    - Packages: 
        - packages/python.md
        - packages/r-libraries.md
        - packages/anaconda.md
    - Running jobs:
        - running-jobs/portal.md
        - running-jobs/slurm-scheduler.md
        - running-jobs/interactive-jobs.md
        - running-jobs/batch-jobs.md
        - running-jobs/resource-requests.md
    - Roar restricted:
        - roar-restricted/accessing-rr.md
        - roar-restricted/data-transfer.md

